site_name: SASP Fase 1
site_url: https://dariomggg.github.io/SASP_Fase1_Web/
nav:
  - Home: index.md
  - SASP: sostenibilidad.md
  - ODS: ods.md
  - Reflexiones: reflexiones.md

theme:
  name: cinder
